[package]
name = "soundfx-rs"
version = "1.0.1-rc.5"
authors = ["jude-lafitteIII <judewrs@gmail.com>"]
edition = "2018"

[dependencies]
serenity = { git = "https://github.com/jellywx/serenity", branch = "jellywx-member_permissions", features = ["voice", "collector"] }
sqlx = { version = "0.3.5", default-features = false, features = ["runtime-tokio", "macros", "mysql", "bigdecimal"] }
dotenv = "0.15"
tokio = { version = "0.2", features = ["fs", "process", "io-util"] }
lazy_static = "1.4"
reqwest = "0.10"
