[package]
name = "soundfx-rs"
version = "1.1.1"
authors = ["jellywx <judesouthworth@pm.me>"]
edition = "2018"

[dependencies]
serenity = { version = "0.10", features = ["voice", "collector"] }
sqlx = { git = "https://github.com/launchbadge/sqlx.git", default-features = false, features = ["runtime-tokio-rustls", "macros", "mysql", "bigdecimal"] }
dotenv = "0.15"
tokio = { version = "1.0", features = ["fs", "process", "io-util"] }
lazy_static = "1.4"
reqwest = "0.11"
songbird = "0.1"
regex = "1.4"
log = "0.4"

[dependencies.regex_command_attr]
path = "./regex_command_attr"
