[package]
name = "soundfx-rs"
version = "0.1.0"
authors = ["jude-lafitteIII <judewrs@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.8"
sqlx = {version = "0.3", features = ["runtime-tokio", "macros"]}
dotenv = "0.15"
