[package]
name = "soundfx-rs"
version = "1.2.0"
authors = ["jellywx <judesouthworth@pm.me>"]
edition = "2018"

[dependencies]
serenity = { version = "0.10", features = ["voice", "collector"] }
sqlx = { version = "0.5", default-features = false, features = ["runtime-tokio-rustls", "macros", "mysql", "bigdecimal"] }
dotenv = "0.15"
tokio = { version = "1.0", features = ["fs", "process", "io-util"] }
lazy_static = "1.4"
reqwest = "0.11"
env_logger = "0.8"
songbird = { git = "https://github.com/serenity-rs/songbird", branch = "current" }
regex = "1.4"
log = "0.4"
serde_json = "1.0"

[dependencies.regex_command_attr]
path = "./regex_command_attr"
